# Generated by Django 3.2.19 on 2023-05-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='recientes')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
            },
        ),
    ]
